### ISSUE TITLE
blender 2.8 RC3 may have broken the addon

### ISSUE THREAD

**Issue by sacrish** [danielenger/Principled-Baker#6]
I've updated blender to 2.80 RC3 and it seems Principled Baker is not working correctly now.

It usually happens when I try to bake (or press detect button on) objects with multiple materials assigned. A typical error message is like this: 

![error message](https://user-images.githubusercontent.com/8361680/62098706-12c5e400-b2be-11e9-8d3b-906fb0a3412e.png)

As far as I remember, the addon used to work fine with RC2. I'm not sure if it's an issue only on my end.

**Comment by danielenger** [comment]
This was a mayor bug. It's fixed now.

**Comment by sacrish** [comment]
Thank you for the work! The major problem has been solved indeed.

However there may still be something not working properly. When I select multiple objects in combine mode, if there are materials that are shared among objects, the output will be solid white color in the area.

I've tested it with both RC3 and the official release, the results are the same.

**Comment by danielenger** [comment]
Should work now.
I forgot just 3 lines of code.

**Comment by sacrish** [comment]
Yes it's working now.
Thank you so much! You are a life saver.

**Comment by deltamish** [comment]
Still persistent in **RC3**

Tried also with 2.81 same issue

![image](https://user-images.githubusercontent.com/9283808/73588638-8527b300-44f1-11ea-86ae-39ddab832fb8.png)

**Comment by deltamish** [comment]
**Update still failing with new errors**
I removed the path and added just a folder name and created same folder within "Blender installation directory". First stage passes now new exception is thrown and all textures are **black**
![image](https://user-images.githubusercontent.com/9283808/73603562-2ffba800-45aa-11ea-97ac-ed3d0eee8c41.png)
